### PR TITLE
OPGOPS-1712 Fix dependency from EC instance on IAM role

### PR DESCRIPTION
**Pull request by carinadigital**

### CODE REVIEW

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test this please

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
ok to test

**Comment by carinadigital** [comment]
test this please

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test this please

**Comment by carinadigital** [comment]
ok to test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Review by brettminnie — APPROVED** [review]

**Pull request merged**
