### PR TITLE
Opgops 1601

### PR DESCRIPTION
**Pull request by brettminnie**
Normalised addition of the target to the security groups for standalone instances, elasticache and rds

Metadata that requires updating

```yaml

elasticache_clusters:
  -
    ec_sg:
      name: ''# remove target or stackname references 
      desc: 'front ec access'
      client_sg: ''# remove target or stackname references 

rds_dbs:
  -
    rds_sg:
      name: ''# remove target or stackname references 
      client_sg: ''# remove target or stackname references 
```

### CODE REVIEW

**Review by tim-mcarthur-moj — COMMENTED** [review]
change looks good, but we need to update metadata in deploy repos before using this.

**Comment by brettminnie** [comment]
:+1: Still a wip, it's not cleaning up properly trying to figure out if
it's meta-data or the destroy code


On Wed, Jan 18, 2017 at 11:56 AM, tim-mcarthur-moj <notifications@github.com

**Comment by tim-mcarthur-moj** [comment]
Please add some info about which group vars are affected by this.

**Comment by brettminnie** [comment]
Will do, working on the rds and elasticache lookups at present

On Thu, Jan 19, 2017 at 10:54 AM, tim-mcarthur-moj <notifications@github.com

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
ok to test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
ok to test

**Comment by carinadigital** [comment]
test this please

**Comment by carinadigital** [comment]
test this please

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
test

**Comment by carinadigital** [comment]
retest

**Comment by carinadigital** [comment]
retest

**Pull request merged**
